modLoader = "kotlinforforge"

loaderVersion = "${loader_version_range}"

license = "${mod_license}"

issueTrackerURL = "https://github.com/tancop/ImmersiveMagic/issues"

[[mods]]

modId = "${mod_id}"

version = "${mod_version}"

displayName = "${mod_name}"

# A URL to query for updates for this mod. See the JSON update specification https://docs.neoforged.net/docs/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://github.com/tancop/ImmersiveMagic"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "logo.png"

# A text field displayed in the mod UI
#credits="" #optional

authors = "${mod_authors}"

description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5.8.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "pistoncommand"
type = "required"
versionRange = "[2.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "immersivemagic.mixins.json"